<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-09 at 15:02:37.
 */
class StyloTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Stylo
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        Zend_Loader::loadClass('Stylo');
        $this->object = new Stylo();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @test
     */
    public function testEcrireNoK() {
       $this->assertEquals('Nok', $this->object->ecrire());
    }
    
    /**
     * @test
     */
    public function testEcrire() {
       $this->assertEquals('ok', $this->object->ecrire());
    }
    
    /**
     * @test
     */
    public function testDessiner() {
       $this->assertTrue($this->object->dessiner());
    }
    
    

}
