<li class="dropdown">
    
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <?php echo $this->translate('projet');?> <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">

         <li class="dropdown-header"><?php echo $this->translate('action');?></li>
         <li><a href="/projet/add"><?php echo $this->translate('add-project');?></a></li>
         <li><a href="/projet/list"><?php echo $this->translate('list-project');?></a></li>

     </ul> 
</li>