<div class='row'>
    <h1>L'équipe du projet SI !!!</h1>
</div>


<div class='row'>
  
  <div class='<?php echo $this->BootTwitterSpanColSML(3)?>'>
    <div class="panel panel-default">
      <div class="panel-heading text-center">
        <h3 class="panel-title">Kévin Berne</h3>
      </div>
      <div class="panel-body text-center">
        <p><img class="img-rounded"  width='121' height='121' src='/images/membres/kevin.jpg' alt='photo de profil'/></p>
        <hr>
        <p>
          <strong>Chargé de communication</strong>
        </p>
      </div>
    </div>
  </div>
  
  <div class='<?php echo $this->BootTwitterSpanColSML(3)?> ' >
    <div class="panel panel-default ">
      <div class="panel-heading text-center" style="background:pink;">
        <h3 class="panel-title">Vincent DUCROQ</h3>
      </div>
      <div class="panel-body text-center">
        <p><img class="img-rounded"  width='121' height='121' src='/images/membres/vincent.jpg' alt='photo de profil'/></p>
        <hr>
        <p>
          <strong>Chef de projet</strong>
        </p>
      </div>
    </div>
  </div>
  
  <div class='<?php echo $this->BootTwitterSpanColSML(3)?>'>
    <div class="panel panel-default">
      <div class="panel-heading text-center">
        <h3 class="panel-title">Assia LACHGAR</h3>
      </div>
      <div class="panel-body text-center">
        <p><img class="img-rounded"  width='121' height='121' src='/images/membres/assia.jpg' alt='photo de profil'/></p>
        <hr>
        <p>
          <strong>MOA</strong>
        </p>
      </div>
    </div>
  </div>
  
  <div class='<?php echo $this->BootTwitterSpanColSML(3)?>'>
    <div class="panel panel-default">
      <div class="panel-heading text-center">
        <h3 class="panel-title">Mickaël ROLO</h3>
      </div>
      <div class="panel-body text-center">
        <p><img class="img-rounded" width='121' height='121' src='/images/membres/mickael.jpg' alt='photo de profil'/></p>
        <hr>
        <p>
          <strong>Développeur Web</strong>
        </p>
      </div>
    </div>
  </div>

</div>
<div class='row'>
  
  <div class='<?php echo $this->BootTwitterSpanColSML(3)?>'>
    <div class="panel panel-default">
      <div class="panel-heading text-center">
        <h3 class="panel-title">Virac STRENG</h3>
      </div>
      <div class="panel-body text-center">
        <p><img class="img-rounded"  width='121' height='121' src='/images/membres/virac.jpg' alt='photo de profil'/></p>
        <hr>
        <p>
          <strong>Intégrateur</strong>
        </p>
      </div>
    </div>
  </div>
  
  <div class='<?php echo $this->BootTwitterSpanColSML(3)?>'>
    <div class="panel panel-default">
      <div class="panel-heading text-center">
        <h3 class="panel-title">Lydie TIAGO</h3>
      </div>
      <div class="panel-body text-center">
        <p><img class="img-rounded"  width='121' height='121' src='/images/membres/lydie.jpg' alt='photo de profil'/></p>
        <hr>
        <p>
          <strong>Chargé de communication</strong>
        </p>
      </div>
    </div>
  </div>
  
  <div class='<?php echo $this->BootTwitterSpanColSML(3)?>'>
    <div class="panel panel-default">
      <div class="panel-heading text-center">
        <h3 class="panel-title">Maly VU</h3>
      </div>
      <div class="panel-body text-center">
        <p><img class="img-rounded"  width='121' height='121' src='/images/membres/maly.bmp' alt='photo de profil'/></p>
        <hr>
        <p>
          <strong>Développeuse web</strong>
        </p>
      </div>
    </div>
  </div>
  
</div>
