<div class='row'>
    <h1>Le blog</h1>
</div>

<div class='row'>
    
    
    <!-- Le corps -->
    <div class='<?php echo $this->BootTwitterSpanCol(8); ?>'>
        
            <div class='row'>
                <form class="" id='f_post' method='post'>
                  <input type='text' id='toto' name='toto' value=''/>
                  <textarea class="ckeditor" rows="5" placeholder="Exprimez vous !" 
                            name='f_post_nouv'></textarea>
                </form>
            </div>


    <div class ="row">

    </div>

</div>
    

