<h1>Ajouter un projet</h1>

<div class='row'>
    <div class='col-lg-5 col-md-5'>
        
        
        <fieldset>
            <legend>Créé à la main</legend>
            <form method='POST'>
                <div class="form-group">
                    <label for='titre'>Titre : </label>
                    <input type='text' name='titre' id='titre'  class="form-control">
                </div>

                 <div class="form-group">
                     <label for='description'>Description : </label>
                     <textarea name='description' id='description' 
                               class="form-control" cols='40' rows="4"></textarea>
                 </div>
                 <button type="submit" class="btn btn-default">Valider</button>
            </form>
        </fieldset>
        
    </div>
    
    <div class='col-lg-5 col-md-5 col-lg-offset-1 col-md-offset-1'>
        <fieldset>
            <legend>Créé avec Zend Form</legend>
            <?php echo $this->form_projet; ?>
        </fieldset>
    </div>
</div>
<hr>


