<h1>Connexion</h1>

<div class='row'>
    <div class='col-xs-7 col-sm-7'>
    <form class="form-horizontal" id='f_insc' method='post'>

        <!-- Login -->

        <div class="form-group" id="login_group">
            <label for="connect_login" class="col-sm-2 control-label">Login</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="connect_login" name="connect_login" placeholder="Login">
                <span id='help_login' class="help-block"></span>
            </div>
        </div>


        <!-- Mot de passe 2 -->

        <div id="password_group" class="form-group">
            <label for="connect_password" class="col-sm-2 control-label"><?php echo $this->translate('mp');?></label>
            <div class="col-sm-9">
                <input type="password" class="form-control" id="connect_password" name="connect_password" placeholder="mot de passe">
            </div>
        </div>


        <!-- Submit -->

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">Se connecter !</button>
            </div>
        </div>

    </form>
    </div>

<!-- JS -->
<script language='javascript'>
  
			
</script>