<h1>Inscription</h1>

<div class='row'>
    <div class='col-xs-7 col-sm-7'>
    <form class="form-horizontal" id='f_insc' method='post'>

        <!-- Login -->

        <div class="form-group" id="login_group">
            <label for="login" class="col-sm-2 control-label">Login</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="login" name="login" placeholder="Login">
                <span id='help_login' class="help-block"></span>
            </div>
        </div>


        <!-- Mot de passe 1 -->

        <div class="form-group">
            <label for="password" class="col-sm-2 control-label">Mot de passe</label>
            <div class="col-sm-9">
                <input type="password" class="form-control" id="password" name="password" placeholder="Mot de passe">
                <span class="help-block" id='help_password1_vide' style='display:none;'>Le mot de passe n'a pas assez de caractères</span>
                <span class="help-block" id='help_password1_securite'>
                    <span class='row'>
                        <span class='col-sm-3'>Sûreté :</span>
                        <span class='col-sm-9'>
                            <div class="progress">
                                <div class="progress-bar progress-bar-success" style="width:0%"  id="password_faible">
                                    <span class="sr-only progress-label">FAIBLE</span>
                                </div>
                                <div class="progress-bar progress-bar-warning" style="width:0%" id="password_moyen">
                                    <span class="sr-only progress-label">MOYEN</span>
                                </div>
                                <div class="progress-bar progress-bar-danger" style="width:0%" id="password_fort">
                                    <span class="sr-only progress-label" >FORT</span>
                                </div>
                            </div>
                        </span>
                    </span>
                </span>
            </div>
        </div>

        <!-- Mot de passe 2 -->

        <div id="password2_group" class="form-group">
            <label for="password2" class="col-sm-2 control-label">Ressaisir le mot de passe</label>
            <div class="col-sm-9">
                <input type="password" class="form-control" id="password2" name="password2" placeholder="Ressaisir le mot de passe">
                <span class="help-block has-warning" id='help_password2' style='display:none;'>Le mot de passe saisi est différent</span>
            </div>
        </div>

        <!-- email -->

        <div class="form-group">
            <label for="f_connect_password" class="col-sm-2 control-label">e-mail</label>
            <div class="col-sm-9">
                <input type="email" class="form-control" id="email" name="email" placeholder="Mot de passe">
                <span id='help_email'>Avec <a href="http://fr.gravatar.com">gravatar</a>, ton image perso sera automatique !</span>
            </div>
        </div>




        <!-- Submit -->

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">S'inscrire !</button>
            </div>
        </div>

    </form>
    </div>

<!-- JS -->
<script language='javascript'>
    
    function checkMp(){
        valid = false;
        if($('#password').val() == '')
        {
            $('#password_faible').css('width','0%');
            $('#password_moyen').css('width','0%');
            $('#password_fort').css('width','0%');
            $('#help_password1_vide').show();
            return false;
        }
        else
        {
            // Doit contenir des majuscules, des chiffres et des minuscules
            var strongRegex = new RegExp("^(?=.{8,})(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])(?=.*\\W).*$", "g");
            // Doit contenir soit des majuscules et des minuscules soit des minuscules et des chiffres
            var mediumRegex = new RegExp("^(?=.{7,})(((?=.*[A-Z])(?=.*[a-z]))|((?=.*[A-Z])(?=.*[0-9]))|((?=.*[a-z])(?=.*[0-9]))).*$", "g");
            // Doit faire au minimum six caractères
            var enoughRegex = new RegExp("(?=.{6,}).*", "g");
            if (false == enoughRegex.test($('#password').val())) 
            {  
                $('#password_faible').css('width','0%');
                $('#password_moyen').css('width','0%');
                $('#password_fort').css('width','0%');
                $('#help_password1_vide').show();
                valid = false;
            } 
             
            else if (strongRegex.test($('#password').val())) 
            {  
                $('#password_faible').css('width','33%');
                $('#password_moyen').css('width','33%');
                $('#password_fort').css('width','34%');
                valid = true;
            } 
             
            else if (mediumRegex.test($('#password').val())) 
            {  
                $('#password_faible').css('width','33%');
                $('#password_moyen').css('width','33%');
                $('#password_fort').css('width','0%');
                valid = true;
                
            } 
            else 
            {
                $('#password_faible').css('width','33%');
                $('#password_moyen').css('width','0%');
                $('#password_fort').css('width','0%');
                valid = true;
            }
        }
        return valid;		
    }
	
    function checkMp2()
    {
        valid = true;
        //penser à vérifier si le password est costaud		
        if($('#password').val() != $('#password2').val())
        {   $('#help_password2').show();
            $('#password2_group').removeClass('has-success').addClass('has-error');
            valid = false;
            
        }
        else if($('#password').val() != '') //s'ils sont égaux c'est bon, sauf si c'est une valeur vide'
        {   $('#help_password2').hide();
            $('#password2_group').removeClass('has-error').addClass('has-success');
        }
				
        return valid;
    }
    
    
    function checkLogin(){
        
        var valid = false;
        
        $('#help_login').html('<img src="/images/loading/1.gif" \n\
                                    alt="recherche de l\'unicité du login en cours..." />');
        
        donnees = { 'login' : $('#login').val()};
	$.ajax({		
		 url: "/user/ajax-check-login",
		 type: "post",
		 data: donnees,
                 async: false,
		 dataType: "json",//on récupère les infos au format json
		 success: function (data) 
		 { 
                     //si data vaut true c'est que le login est déjà utilisé
                     if(data == true){
                         $('#login_group').removeClass('has-success').addClass('has-error');
                         $('#help_login').html('Ce login est déjà utilisé');
                         valid = false;
                     }else{
                         $('#login_group').removeClass('has-error').addClass('has-success');
                         $('#help_login').html('Ce login est libre');
                         valid =true;
                     }
		     
		 },
											 
		 error: function() 
		 { 
			alert('Echec de la requète ..');
                        valid = false;
		 }
											 
	     });
        
        return valid;
    }
		
    $(function(){
        $('#password').keyup(function(touche){
            checkMp();
        });
        $('#password').blur(function(touche){
            checkMp();
        });
        
        $('#password2').blur(function(touche){
            checkMp2();
        });
        
        $('#login').blur(function(touche){
           checkLogin(); 
        });
        
        $('#f_insc').submit(function() 
        {
            validMp = checkMp();
            validMp2 = checkMp2();
            validLogin = checkLogin();
            if(validLogin == false){
                alert('Login invalide');
            }
            
            if((validMp == true) && (validMp2 == true) && (validLogin == true))
            {
                return true;
            }else{
                alert('L\'une des informations ne respectent pas les critères');
                return false;
            }
        });
			   
    });
			
</script>