
<?php $this->headTitle('Connexion'); ?>

<h1>Connexion</h1>

<form class="form-horizontal" id='f_connect' method='post'>
    
    <!-- Login -->

        <div class="form-group">
          <label for="f_connect_login" class="col-sm-2 control-label">Login</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" id="f_connect_login" name="f_connect_login" placeholder="Login">
          </div>
        </div>
    
    
    <!-- Mot de passe 1 -->

        <div class="form-group">
          <label for="f_connect_mp" class="col-sm-2 control-label">Mot de passe</label>
          <div class="col-sm-10">
            <input type="password" class="form-control" id="f_connect_mp" name="f_connect_mp" placeholder="Mot de passe">
          </div>
        </div>
    
    
    <!-- Submit -->
    
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-default">Se connecter !</button>
            </div>
        </div>

</form>
