<?php
$auth = Zend_Auth::getInstance();
$user = $auth->getStorage()->read();
?>

<ul class="nav navbar-nav">

    <li>
        <a href="/user/profil">
            <img src='http://www.gravatar.com/avatar/<?php echo $user->gravatar_user; ?>?s=20' alt='' />
        </a>
    </li>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <?php echo $user->login_user;?> 
             <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="/user/profil">Profil</a></li>
            <li class="divider"></li>
            <li><a href="/user/deconnexion">Deconnexion</a></li>
        </ul> 
    </li>


</ul>