<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Zend</a>
    </div>

    <div class="navbar-collapse collapse">

      <!-- Le menu -->
      <ul class="nav navbar-nav">
        <?php echo $this->render('navbar/menubyrole/' . $this->getRole() . '.phtml'); ?>
      </ul>

      
      
        <?php
         echo $this->render('navbar/menudroite/menudroite.phtml');
        ?>

    </div><!--/.navbar-collapse -->
  </div><!-- /container -->
</div>